services:
  selenium:
    image: seleniarm/standalone-chromium
    hostname: selenium
    ports:
      - "4444:4444"
    volumes:
      - ../downloads:/app/downloads
      - /dev/shm:/dev/shm

  ruby:
    build:
      context: ../
      dockerfile: M1/Dockerfile
    depends_on:
      - selenium
    env_file:
      - ../.env.local
    environment:
      SELENIUM_HOST: selenium:4444
      M1_LOCAL: true
    volumes:
      - ../:/app
