version: '3'

services:
  selenium:
    image: seleniarm/standalone-chromium # if M2 Mac
    # image: selenium/standalone-chrome # if other
    ports:
      - "4444:4444"
    volumes:
      - ./downloads:/home/seluser/downloads

  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium
    environment:
      - SE_EVENT_BUS_HOST=selenium
    volumes:
      - /dev/shm:/dev/shm

  ruby:
    build: .
    depends_on:
      - chrome
    env_file:
      - .env.local
    environment:
      SELENIUM_HOST: selenium:4444
    volumes:
      - .:/app
      - ./downloads:/app/downloads